module.exports = {
  globals: {
    GM: 'readonly',
    GM_addElement: 'readonly',
    GM_addStyle: 'readonly',
    GM_addValueChangeListener: 'readonly',
    GM_deleteValue: 'readonly',
    GM_download: 'readonly',
    GM_getResourceText: 'readonly',
    GM_getResourceURL: 'readonly',
    GM_getTab: 'readonly',
    GM_getTabs: 'readonly',
    GM_getValue: 'readonly',
    GM_info: 'readonly',
    GM_listValues: 'readonly',
    GM_log: 'readonly',
    GM_notification: 'readonly',
    GM_openInTab: 'readonly',
    GM_registerMenuCommand: 'readonly',
    GM_removeValueChangeListener: 'readonly',
    GM_saveTab: 'readonly',
    GM_setClipboard: 'readonly',
    GM_setValue: 'readonly',
    GM_unregisterMenuCommand: 'readonly',
    GM_xmlhttpRequest: 'readonly',
    unsafeWindow: 'readonly',
  },
};
