module.exports = {
  globals: {
    GM: 'writable',
    GM_addElement: 'writable',
    GM_addStyle: 'writable',
    GM_addValueChangeListener: 'writable',
    GM_deleteValue: 'writable',
    GM_download: 'writable',
    GM_getResourceText: 'writable',
    GM_getResourceURL: 'writable',
    GM_getTab: 'writable',
    GM_getTabs: 'writable',
    GM_getValue: 'writable',
    GM_info: 'writable',
    GM_listValues: 'writable',
    GM_log: 'writable',
    GM_notification: 'writable',
    GM_openInTab: 'writable',
    GM_registerMenuCommand: 'writable',
    GM_removeValueChangeListener: 'writable',
    GM_saveTab: 'writable',
    GM_setClipboard: 'writable',
    GM_setValue: 'writable',
    GM_unregisterMenuCommand: 'writable',
    GM_xmlhttpRequest: 'writable',
    unsafeWindow: 'writable',
  },
};
